### ISSUE TITLE
Could AC-SGD be working with like deepspeed zero2/3?

### ISSUE THREAD

**Issue by leiwen83** [DS3Lab/AC-SGD#1]
Hi,

I want to know that whether this compression algo could be working with deepspeed's zero or torch's fsdp?

Thx

**Comment by BinhangYuan** [comment]
Hi @leiwen83 ，

Briefly, we do not have an implementation to support this yet. On the other hand, these two techniques are orthogonal, you can definitely apply these together since FSDP or ZeRO do not relax any computation. 

You are more than welcome to contribute a PR in this open-source project to enable this!

Best wishes,
Binhang
